[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 110
lines = 30


#[shell]
# program = "wsl ~"

# KDE Breeze (Ported from Konsole)
# Default colors
[colors.primary]

background = '#232627'
foreground = '#fcfcfc'
dim_foreground = '#eff0f1'
bright_foreground = '#ffffff'


# Normal colors
[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#f67400'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'

white = '#fcfcfc'


# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'

white = '#ffffff'


# Dim colors
[colors.dim]

black = '#31363b'
red = '#783228'

green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'

[font]
size = 14

  [font.normal]
  family = "CodeNewRoman Nerd Font"
  style = "Regular"

  [font.bold]
  family = "CodeNewRoman Nerd Font"
  style = "Bold"


  [font.italic]
  family = "CodeNewRoman Nerd Font"
  style = "Italic"

[keyboard]
  [[keyboard.bindings]]
    key = "Slash"
    mods = "Control"
    chars = "\u001f"
  [[keyboard.bindings]]
    key = "F"
    mods = "Alt"
    action = "ToggleFullscreen"
