return {
  s({
    trig = "solve-once",
    dscr = "create a template to solve problem once",
  }, {
    t({
      "#include<bits/stdc++.h>",
      "using namespace std;",
      "#define ll long long",
      "",
      "int main() {",
      "  ios::sync_with_stdio(false);",
      "  cin.tie(0);",
      "  return 0;",
      "}",
    }),
  }),
  s({
    trig = "solve-by-times",
    dscr = "create a template to solve problem once",
  }, {
    t({
      "#include<bits/stdc++.h>",
      "using namespace std;",
      "#define ll long long",
      "",
      "void solve();",
      "",
      "int main() {",
      "  ios::sync_with_stdio(false);",
      "  cin.tie(0);",
      "  int t;",
      "  cin >> t;",
      "  while (t--) {",
      "    solve();",
      "  }",
      "  return 0;",
      "}",
      "",
      "void solve() {",
      "",
      "}",
    }),
  }),
  s("trigger", {
    t({ "After expanding, the cursor is here ->" }),
    i(1),
    t({ "", "After jumping forward once, cursor is here ->" }),
    i(2),
    t({ "", "After jumping once more, the snippet is exited there ->" }),
    i(0),
  }),
}
