DOTDIR=~/.dotfiles

# init history
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory

source $DOTDIR/zsh/plugin.zsh
source $DOTDIR/zsh/prompt.zsh
source $DOTDIR/aliases/aliases.sh